mysql:
  path: 119.29.231.12
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: 学习数据库
  username: 学习数据库
  password: xyd4dLKrhinnKWdZ
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false
jwt:
  signing-key: 'JerryZou'
  expires-time: 604800
  buffer-time: 86400
  issuer: 'JerryZou'
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
# system:
#   env: public
#   addr: 8080
#   db-type: mysql
#   oss-type: local
#   use-multipoint: false
#   use-redis: false
#   limit-count-ip: 15000
#   limit-time-ip: 3600
# zap:
#   level: info
#   format: console
#   prefix: 'Shansec'
#   director: log
#   show-line: true
#   encode-level: LowercaseColorLevelEncoder
#   stacktrace-key: stacktrace
#   log-in-console: true